name: Python Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      ENABLE_COVERAGE: ${{ matrix.ENABLE_COVERAGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "latest"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build-core pybind11

      - name: Build
        run: |
          pip install -e ".[test]"

      - name: Lint
        run: |
          black --check sp_svg_diagram python/tests
          isort --check-only sp_svg_diagram python/tests
          flake8 sp_svg_diagram python/tests

      - name: Test
        run: |
          pytest python/tests
